version: '3'
volumes:
  movie_data:
    external: true

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - database
    volumes:
      - /app/node_modules
      - ${PWD}/:/app
    ports:
      - '5000:5000'
    env_file:
      - .env
    environment:
      PORT: 5000
      DATABASE_URL: postgres://postgres:postgres@database/movies
    entrypoint:
      - /app/entrypoint.sh
    command:
      - yarn
      - start:dev
    depends_on:
      - database
  database:
    image: postgres:12-alpine
    expose:
      - '5432'
    ports:
      - '5433:5432'
    volumes:
      - movie_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movies
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 10s
      retries: 5
